### ISSUE TITLE
Problema com Icones

### ISSUE THREAD

**Issue by GamingTechEdu** [coocree/coocree_kdl#1]
Boa tarde,

Estou com problemas para incluir os icones no projetos, dei uma olhada e eles estão no formato SVG.

**Comment by coocree** [comment]
Para implementer os icones svg que estão na pastas de recursos você deve utilizar o pacote: 
https://pub.dev/packages/flutter_svg

Os icones deve ser renomeados para estar de acordo com o botão onde será utilizado, por exemplo:
add_box_FILL0_wght400_GRAD0_opsz48.svg = include.svg
